version: '3'

services:
  publisher:
    image: publisher
    tty: true
    depends_on:
      - mq
  mq:
    image: rabbitmq:3.7.4-management
    ports:
      - '5672:5672'
      - '15672:15672'
  consumer:
    image: consumer
    tty: true
    volumes:
      - ./consumer:/usr/src/myapp
    depends_on:
      - mq